GET  http://localhost:5000/blogs/ HTTP/1.1

###
POST http://localhost:5000/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "My first blog"
}

###
PUT http://localhost:5000/blogs/7xgRGABNG1Ac8AlVfLtq HTTP/1.1
content-type: application/json

{
    "title": "My first blog 2"
}

###
GET  http://localhost:5000/blogs/7xgRGABNG1Ac8AlVfLtq HTTP/1.1

###
DELETE  http://localhost:5000/blogs/7xgRGABNG1Ac8AlVfLtq HTTP/1.1
